### ISSUE TITLE
Sponsor: Where are the buttons beneath each package that link to Kyle's commit and pay page

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#105]
Were you waiting to add these until he finishes that page, or is their absence an oversight?

**Comment by mattada** [comment]
No idea. I dont have any URLs for those. They will need to be in the wp-content.

**Comment by mbalkon** [comment]
Ok, good to know. They all go the same place, so it should be easy... plus, did you see I added my OWN button to the Compare Conferences site! Yes, I'm inspecting and stealing code!!! :)

**Comment by mbalkon** [comment]
I'm going to close this. I can add these myself when we get the URL.

**Comment by mattada** [comment]
the links will need a ‘class=“button”’ added to them, fyi.

Matt Adams
mattadams@factor1studios.com  |  twitter.com/mattada

_factor1_
factor1studios.com  |  twitter.com/factor1
602.334.4806 office  |  602.509.7553 mobile
