### ISSUE TITLE
Speaker – Charles Anderson: Fix gap between headshot and work image and make sure images are the same height

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#106]
![screenshot 2016-07-22 19 13 48](https://cloud.githubusercontent.com/assets/4261229/17075182/73141dd8-5040-11e6-8e9c-54485a556083.png)

**Comment by mbalkon** [comment]
Nevermind, I fixed it myself!

**Comment by mattada** [comment]
Was it an original size issue?

#Sentfrommyiphone
Matt Adams
6025097553

Creative Director
factor1studios.com

**Comment by mbalkon** [comment]
Yes I think so. I think you'd uploaded this slice and we must have made some slight adjustments to the container size while QA-ing. So I just uploaded a new image and it worked! I'm practically a developer!!! I even closed an issue for once! ;)

**Comment by mattada** [comment]
Lol

#Sentfrommyiphone
Matt Adams
6025097553

Creative Director
factor1studios.com
