### ISSUE TITLE
Conference: Add hover state to speaker photos/text

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#107]
What do you think we can do here to demonstrate these are clickable? Perhaps a color overlay? Can we give the copy a hover state too?

**Comment by mbalkon** [comment]
I think a **blue** overlay on the photo should work for a hover state – 50% transparent

For the text, we can just roll over to the **same color of blue**

See mockup below:

![phxdw-mm-conference-hover-fnl](https://cloud.githubusercontent.com/assets/4261229/17091853/1e8bb154-51f3-11e6-8272-48e321a5ab0c.jpg)

**Comment by mattada** [comment]
Okay That may work. I need to process that more later today.

**Comment by mbalkon** [comment]
Hey Matt! I just wanted to check on this. Per your message earlier this week, if lightening the photos is easier (rather than doing an overly), I would absolutely be game to see if that could work instead.

**Comment by mattada** [comment]
http://factor1.me/2016/phxdw/method-and-madness-conference/

Still tweaking but its super close.

**Comment by mbalkon** [comment]
Yay yay yay! A billion times better!

---

Melissa Balkon
_Founder + Design Strategist, Strong Design_
_Creative Director, Phoenix Design Week 2016_

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

Check out our new Etsy shop https://www.etsy.com/shop/StrongDesignGoods/!
