### ISSUE TITLE
Global: Change the capitalization on H2s throughout the site to sentence case

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#113]
I'm sorry, please don't hate us....

Kathy pointed out that there are a lot of H2s that have initial caps on all of the words, and that is trickier to read. I would do this, but I think most are hard-coded so.... Let me know if there is anything I can do to help!

**Comment by mattada** [comment]
I removed the few I saw in the hard coded sections and set the h2 h3 combo from Caps to none. Should be good.

**Comment by mbalkon** [comment]
Could you fix the following ones:
- Email sign-up headline H2
- Sponsor band headline H2
- "And" in "Premier Print And Large Format Sponsor"
- Sponsor section >> Partner Organizations Who Helped Organize This Event
- Conference page H2 headlines in the promo boxes (all 4 of them)
- About page H2 headlines in the 2 promo boxes at the bottom of the page
