### ISSUE TITLE
Conference (mobile): Make sure the hero headline is centered on mobile

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#126]
![2016-07-23 20 50 40](https://cloud.githubusercontent.com/assets/4261229/17081712/dd687602-5117-11e6-8832-b4cbfd4868f9.png)

**Comment by mattada** [comment]
Fixed with #117 but could still be an issue on tighter phones. The word "conference" at that size is wider than allotted. The reduced padding should help, but we also increased the h1 per #117, so they could wash.
