### ISSUE TITLE
Compare Conferences (mobile): Fix hero headline alignment to be centered

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#130]

**Comment by mattada** [comment]
The increase in h1 per #117 didnt help this issue. H1s on mobile are very large. 

Do we one off fix the remaining issues to be smaller on phones or globally get h1s 15% smaller?

**Comment by mbalkon** [comment]
I say go with making the H1s smaller again. Sorry, I didn't realize that would end up causing a problem.
