### ISSUE TITLE
Student Sponsor App (mobile): Fix hero headline alignment to be centered

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#131]

**Comment by mattada** [comment]
Ditto to #130 H1's are too big for the space  available.

**Comment by mbalkon** [comment]
Ok. They seem to be showing, they are just off-center. Here's a screenshot... See how the text fits, but it just off center?

Also, if we need to undo my request to increase the H1 size, we can. I didn't realize it was an issue you'd been battling.

![2016-07-24 00 19 10](https://cloud.githubusercontent.com/assets/4261229/17082467/5b010a0e-5134-11e6-972d-a1025df35024.png)

**Comment by mattada** [comment]
It's because there is padding on the left and right but the text is overflowing the right padding.

#Sentfrommyiphone
Matt Adams
6025097553

Creative Director
factor1studios.com

**Comment by mbalkon** [comment]
Gotcha. Ok. Feel free to decrease the size of the H1s then so that they better fit. We might just have to decrease the size of the subheads beneath the H1s (where applicable) to make sure they keep reading as follow-up info to the main H1.
