### ISSUE TITLE
Global: Is there a way to convert all of the quote marks in the photo bands to be true curly quotes, not inch marks?

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#134]

**Comment by mattada** [comment]
Globally no. They have to be encoded. The internet / HTML doesnt handle them by default and they have to be ascii code.

**Comment by mbalkon** [comment]
OK. This is going to drive Kathy (and a lot of designers) nuts. What can we do about it? I'm totally willing to help however I can!

**Comment by mbalkon** [comment]
PS, I/we are not looking to update every single quote mark on the site, just the big photo bands with testimonials on them:

Conference page
Compare Conferences page
