### ISSUE TITLE
Sponsor: Need to link up .pdf downloads

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#139]
There are two instances of this; in the hero and at the very bottom

I uploaded the sponsor packet to the media section

**Comment by mattada** [comment]
Is this a new pdf? 

Currently both link to: http://phxdw.com/wp-content/uploads/2016/06/phxdw-2016-sponsorship-packet-051316.pdf

**Comment by mbalkon** [comment]
That is the correct one. For some reason Kathy said they didn't link. Maybe they just downloaded on her browser and she didn't realize. I'll CLOSE this one!!
