### ISSUE TITLE
Conference (table, vertical): Reduce bottom padding on ticket price boxes

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#151]
![photo jul 24 9 41 05 pm](https://cloud.githubusercontent.com/assets/4261229/17090677/a32a48a0-51e7-11e6-8eeb-1c6715c37980.png)

**Comment by mattada** [comment]
All set. these were super goofy on smaller screens since I built them with an aspect ratio to match the design. I dropped that globally and now they are more flexible.
