### ISSUE TITLE
Global: Add first name and last name fields (required) to email signup

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#153]

**Comment by mbalkon** [comment]
This was a leftover task from last night that I was waiting for clarification on. It is non-urgent, but Kathy would like it because their mailing list is a mess and they'd like to start getting full contact info.

**Comment by mattada** [comment]
Yeah i saw that on BaseCamp. It will probably impact the layout.

Matt Adams
mattadams@factor1studios.com  |  twitter.com/mattada

_factor1_
factor1studios.com  |  twitter.com/factor1
602.334.4806 office  |  602.509.7553 mobile

**Comment by mbalkon** [comment]
Meaning we can't do it, or I need to redesign that section? If we need to redesign, do you have a recommendation that will be the most friendly across devices? (at this point, I just want to cause the fewest waves for you guys...)

**Comment by mattada** [comment]
We just need to update the code and deal with the update view of it. We may
be able to float the 3 inputs and wrap the button down, then stack all on
smaller screens.

**Comment by mbalkon** [comment]
Sounds like a good solution to me!

---

Melissa Balkon
_Founder + Design Strategist, Strong Design_
_Creative Director, Phoenix Design Week 2016_

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

Check out our new Etsy shop https://www.etsy.com/shop/StrongDesignGoods/!
