### ISSUE TITLE
About: Please add Lisa Altomare's name to the team list (see comment)

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#157]
Lisa's title should be "Communications Support" and we should place her where Liz Hallbeck's name currently is.

**Comment by mattada** [comment]
Okay all set, and I made it better. 

Now you can manage these on the about page :)

![screen shot 2016-08-03 at 2 41 45 pm](https://cloud.githubusercontent.com/assets/10223806/17382981/78d4deb4-5988-11e6-905d-4bcbfae0c247.png)

**Comment by mbalkon** [comment]
Yay for me managing it myself! Had I known we'd have this many changes I
would have specified that as a requirement in the beginning... ;)

---

Melissa Balkon
_Founder + Design Strategist, Strong Design_
_Creative Director, Phoenix Design Week 2016_

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

Check out our new Etsy shop https://www.etsy.com/shop/StrongDesignGoods/!
