### ISSUE TITLE
Home page: Change dates to October 21-28

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#158]
It currently says 22-28, but should be 21-28. Sorry about that oversight!

**Comment by mbalkon** [comment]
Hey Eric! Can you change the CONFERENCE page dates back to October 22-23 (not the 21st). The 21st is part of PHXDW, but not Method + Madness. I had originally posted this request wrong.

**Comment by erwstout** [comment]
Got it. Updated!

**Comment by mbalkon** [comment]
Thanks!

---

Melissa Balkon
_Founder + Design Strategist, Strong Design_
_Creative Director, Phoenix Design Week 2016_

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

Check out our new Etsy shop https://www.etsy.com/shop/StrongDesignGoods/!
