### ISSUE TITLE
Make sure ticket pricing changes as midnight, August 31 (see notes)

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#159]
Hey all!

We need to change the ticket pricing on the Conference page to the following structure at midnight on August 31st.

AIGA Member General Admission $299
AIGA Non-Member General Admission $369
AIGA Member Student Admission $99
AIGA Non-Member Student Admission $149

Note: We also need to change the headline above it to say "Get your Method + Madness tickets now!"

**THEN....**

On Monday the 5th we need to change the pricing BACK to the Advance tickets pricing, outlined below. Note: The headline can remain as I noted it above.

AIGA Member General Admission $199
AIGA Non-Member General Admission $269
AIGA Member Student Admission $99
AIGA Non-Member Student Admission $129

This pricing will stay good until Midnight, September 9th. After midnight on September 9th, it needs to change BACK to the pricing I listed above (noted again below), and this is where it should stay until the event.

AIGA Member General Admission $299
AIGA Non-Member General Admission $369
AIGA Member Student Admission $99
AIGA Non-Member Student Admission $149

I'm sorry for all the changing.... but people are weird and we have to do these weird pricing tricks to motivate them to buy their tickets already.

**Comment by mattada** [comment]
Staged and ready to deploy. 
http://factor1.me/2016/phxdw/method-and-madness-conference/

**Comment by mbalkon** [comment]
Hey guys!

In case you didn’t see the Basecamp message.... the team decided to use a promo code for the “flash sale” next week... so no more changes will be needed by you guys to the pricing after tonight!

**Comment by erwstout** [comment]
I was not a part of these updates so I'm not sure exactly what the directive is here, but I was going to push everything that Matt had worked on (including the price change) tonight at midnight, does that affect anything at all?

**Comment by mattada** [comment]
okay to push live. This has no effect on the midnight price change.

Matt Adams
mattadams@factor1studios.com  |  twitter.com/mattada

_factor1_
factor1studios.com  |  twitter.com/factor1
602.334.4806 office  |  602.509.7553 mobile

**Comment by erwstout** [comment]
Awesome, thanks.

**Comment by erwstout** [comment]
I pushed live!

One thing I noticed not on the wordpress side is Event Bright says the event sale has ended and there are no tickets to purchase... Just a heads up.

**Comment by mbalkon** [comment]
Thanks for the heads-up Eric... Kathy MIGHT have been in the process of
switching that... I'll ask her :)

---

Melissa Balkon
_Founder + Design Strategist, Strong Design_
_Creative Director, Phoenix Design Week 2016_

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

Check out our new Etsy shop https://www.etsy.com/shop/StrongDesignGoods/!
