### ISSUE TITLE
Add "Other Sponsors" section to global site footer

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#160]
I'm trying to be proactive here... in my past experience, the sponsorship team inevitably ends up working last minute deals with sponsors for swag inclusion, etc..... things that don't fit neatly into a level. For example, BoomPromo just signed on to sponsor lanyards, but I'm not sure that actually puts them into any one level. Could we add an "other" category to the site?

In fact, while we're at it, could we add a "Student Sponsors" section beneath the "Other" section? Just in case the team want them separated.... just trying to get ahead of the inevitable request.

**Comment by mbalkon** [comment]
Could I get an update on when this might be done? I'd just rather have it done sooner than later, because it is highly likely the sponsor team will log a bunch of random sponsors at the last second and we'll have to add a bunch of logos immediately.

**Comment by mattada** [comment]
All set. Section are hidden until sponsors are added automagicaly (aka just basic php logic).

**Comment by mbalkon** [comment]
Thank you!!

---

Melissa Balkon
_Founder + Design Strategist, Strong Design_
_Creative Director, Phoenix Design Week 2016_

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

Check out our new Etsy shop https://www.etsy.com/shop/StrongDesignGoods/!

 _NOTE:_ I will be out of the office September 17-27. Please let me know if
you need anything prior to that time.
