### ISSUE TITLE
Fix button styling on sponsorship page

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#162]
Hi guys!

I just FINALLY added the "Commit to this sponsorship" buttons to the Sponsorship page (to each level), but they seem to be picking up the yellow link styling from each level, which makes the text almost unreadable on the white button. Could you please adjust this so that the button TEXT is either the dark blue color (same as the background of the boxes) or the teal color?

**Comment by mattada** [comment]
So the purple was kind of bland, what about teal? I kept the hover to yellow since the BG on the button fades to $purple

**Comment by mbalkon** [comment]
I'm a-ok with teal! I can't see it yet though on the live site.
