### ISSUE TITLE
 Checkout - Divider/spacing between attendee info

### ISSUE THREAD

**Issue by mattada** [factor1/phoenix-design-week-2016#18]
![image](https://cloud.githubusercontent.com/assets/10223806/14749878/d2427e2e-0876-11e6-8ed3-293ea918afa1.png)

**Comment by mattada** [comment]
Asking Melissa: Whats the desired update here? A HR between attendee 1 and 2?

**Comment by mbalkon** [comment]
I think this was Robert's comment, but yes, I do think and HR between Attendee 1 and 2 would be a good idea, or a subhead above each section "Information for Attendee 1"... "Information for Attendee 2"

**Comment by mattada** [comment]
So the good news here @erwstout is that the first `<p>` of each attendee has an ID of `16_attendee_#_field`. So in theory, we could add a border top on all `16_attendee_2_field` and above, i assume 2 - 10.

**Comment by mattada** [comment]
Or use the bottom company field id `16_attendeecompany_1_field`

**Comment by erwstout** [comment]
25fe30b
