### ISSUE TITLE
Home - Email subscribe - Error message upon subscribe (see comment)

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#27]
I have yet to be able to successfully subscribe to the email list through this form. I was getting the attached error last night and also today. 
![screenshot 2016-04-22 13 23 48](https://cloud.githubusercontent.com/assets/4261229/14754015/a0316668-088d-11e6-9fe2-7e738ee9d583.png)

**Comment by mattada** [comment]
This is probably because you are already on the list. This is 100% mailchimp and not much we can do about it.

**Comment by mbalkon** [comment]
OK. But you can confirm it has been tested and is working correctly?

**Comment by mattada** [comment]
yes, it did work with a new email. Try mbalkon+test@gmail.com

**Comment by mbalkon** [comment]
I just tried it and am still getting the error...

**Comment by erwstout** [comment]
It worked with my testing / emails.

**Comment by erwstout** [comment]
![screen shot 2016-04-22 at 2 02 50 pm](https://cloud.githubusercontent.com/assets/9441913/14754848/f2b28c78-0892-11e6-886a-fc2918980d83.png)
