### ISSUE TITLE
Home - Tickets box - Add disclaimer in italics beneath conference dates

### ISSUE THREAD

**Issue by mattada** [factor1/phoenix-design-week-2016#3]
Early Bird tickets include PHXDW Opening Party on October 21 and PHXDW Closing Party October 28

New image: 
![early-bird-disclaimer-text-styling](https://cloud.githubusercontent.com/assets/10223806/14749716/fb5e3b1e-0875-11e6-9112-11cca51326a7.png)

**Comment by erwstout** [comment]
4a41b31

**Comment by erwstout** [comment]
Incorrect. Fixing.

**Comment by erwstout** [comment]
83cb48f
