### ISSUE TITLE
Product page - Is it possible to add a 5th field to the attendee info requesting their Job Title?

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#30]

**Comment by mattada** [comment]
Sorry I cant. Its just not part of the event attendee data set. I can add it, but its only for one, like the AIGA and student ID. 

Which brings up a new issue, what if I need 3 AIGA and 1 general. I cant offer 3 AIGA member fields.

**Comment by mbalkon** [comment]
Ok. It is what it is!

**Comment by mattada** [comment]
Closing since we no longer need these product pages
