### ISSUE TITLE
Product page - Revise disclaimer beneath product name (see comment)

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#31]
Please place this text for now (I'm pretty sure Kathy will edit this still):

Group orders are currently capped at 3 attendees, if you have a larger group simply process additional orders as needed. Group discounts are not available on Early Bird tickets. Please refer to Terms and Conditions for more information. 

**Make sure to link the T&Cs text**

**Comment by mbalkon** [comment]
PS, if it makes things any easier, I would also be ok with this text beneath the "Add to order" button.

**Comment by mattada** [comment]
all set
