### ISSUE TITLE
Global: Adjust pink hero headline color to #ee41aa

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#40]
In fact, all instances of hot pink THROUGHOUT the site should be #ee41aa

![screenshot 2016-07-16 22 31 40](https://cloud.githubusercontent.com/assets/4261229/16898941/1942102a-4ba5-11e6-82b8-6a9ca1774f7c.png)

**Comment by mattada** [comment]
Hmm okay, but it is. 

`$pink:        #ee41aa;`

**Comment by mbalkon** [comment]
So weird. It looks like a completely different shade of pink (that doesn't match the pattern) on my laptop! I guess this one is a-ok then!
