### ISSUE TITLE
Global: H3s should be Proxima Nova Regular, not Bebas

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#43]
They are 40px in the .psd mockups and should be in standard sentence-case (not all caps). They should be the same as the email signup headline styling (note, the email signup headline may have to reduce just a bit along with this change).

![screenshot 2016-07-16 22 43 44](https://cloud.githubusercontent.com/assets/4261229/16898963/c8048ede-4ba6-11e6-83d7-cb1b37d39e77.png)

**Comment by mattada** [comment]
All set with issue #41

**Comment by mbalkon** [comment]
I'm sorry, I wasn't clear enough. Although the font was updated this still isn't correct—these headlines should be in sentence case, regular weight and the same size as the H2s (basically they are exactly the same as the H2s—I'm not sure why they aren't just styled as H2s, but I leave that to you and your team's expertise! :)
