### ISSUE TITLE
Global: Increase stroke weight on button hovers

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#45]
It looks like these strokes are currently 2px—could we increase them to 4 or 5 px stroke weight? Its ok if the buttons have to get a bit taller in order to do this.

![screenshot 2016-07-16 22 49 05](https://cloud.githubusercontent.com/assets/4261229/16898988/8bbbf1f0-4ba7-11e6-89f0-0833d8e48fa6.png)

**Comment by mattada** [comment]
I worry 5 is a lot. 
![screen shot 2016-07-18 at 8 59 45 pm](https://cloud.githubusercontent.com/assets/10223806/16938247/9f3ddfd4-4d2a-11e6-95bc-da4f8af49c20.png)
