### ISSUE TITLE
Global: Even out the padding above and below email signup band content

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#46]
The padding above the email signup headline is greater than the padding that follows the button. Doubling the amount on the bottom should pretty much even it out.

![screenshot 2016-07-16 22 52 45](https://cloud.githubusercontent.com/assets/4261229/16898999/0d3af3ca-4ba8-11e6-85a1-f96f5c4e3b0a.png)

**Comment by mattada** [comment]
So the root issue is that the padding is the same, but the pattern on the bottom is part of that total padding. 

I reduced the top padding by half. Thought @mbalkon ?

**Comment by mbalkon** [comment]
This is improving. Is it possible to only add padding to the bottom and not have it effect the top padding? If so another ~20px of padding between the form and the yellow/lime pattern would be good.
