### ISSUE TITLE
Global (?): Even out padding on full-width photo bands

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#49]
Each of the places the photo band treatments are in use, there seems to be more space above the text (headline and description) than below it. I think the border treatment is actually part of that band, but we just need to offset that border. Could we even this out?

![screenshot 2016-07-16 23 04 08](https://cloud.githubusercontent.com/assets/4261229/16899034/a2c1e754-4ba9-11e6-8533-c33475f024d3.png)

![screenshot 2016-07-16 23 04 54](https://cloud.githubusercontent.com/assets/4261229/16899037/d81c84ea-4ba9-11e6-9769-4764c2d94f8f.png)

**Comment by mattada** [comment]
Same padding issue ad #46

**Comment by mbalkon** [comment]
I'm sorry, but this is looking too tight now. Can we add some more padding to both the top and the bottom—Around 20px to the top and 20px to the bottom.
