### ISSUE TITLE
MM Conference: Update styling on Ticket Pricing headline to be Proxima Nova

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#54]
This headline should have the same styling as all of the other H2s that are in Proxima Nova.

![screenshot 2016-07-16 23 20 52](https://cloud.githubusercontent.com/assets/4261229/16899096/16054eb6-4bac-11e6-9429-3572f5512535.png)

**Comment by mattada** [comment]
Fixed with issue #41

**Comment by mbalkon** [comment]
Again, I wasn't clear enough here. This needs to be regular weight and sentence case as well.

The "Prices go up" should be bolded (but sentence case)
