### ISSUE TITLE
About: Revise styling on learn about MM and check out events box headlines

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#57]
These headlines need to be in Proxima Nova as well—same styling as previous specs given for H2s and H3s. Basically every H-tag needs to be in Proxima Nova. Only buttons use the Bebas, and a couple subheads in the hero areas.

![screenshot 2016-07-16 23 34 51](https://cloud.githubusercontent.com/assets/4261229/16899158/57393fd0-4bae-11e6-9c39-b8902bcb921c.png)

**Comment by mattada** [comment]
fixed with issue #41

**Comment by mbalkon** [comment]
Again, I failed to provide all of the details here: They also need to be regular weight and sentence case (I think I noted this in Issue #41 as well)
