### ISSUE TITLE
About: Apply same styling from Issue #53 to two boxes at the bottom of this page

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#61]
![screenshot 2016-07-18 22 21 16](https://cloud.githubusercontent.com/assets/4261229/16939381/f91fde66-4d35-11e6-8417-6653a956979e.png)

**Comment by mattada** [comment]
Soo...... this is a responsive content issue. The left has almost double the content. The taller column wins and the other adjusts.

**Comment by mbalkon** [comment]
Oh, what I meant here is that this is another H3/H2 issue. The headlines need to be sentence case and regular weight as requested in Issue #53 (basically, they need to be styled like H2s)

**Comment by mattada** [comment]
Okay got it. Changes to #53 / #68 are live now.
