### ISSUE TITLE
Global: Change dropdown nav background to #8348ad

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#64]
I can't quite figure out if it is right or not, but the dropdown background should be #8348ad

Also, is there any way we can remove the scrollbar for the drop-down? Right now, there shouldn't be a need to scroll on desktop.

![screenshot 2016-07-18 22 43 53](https://cloud.githubusercontent.com/assets/4261229/16939726/20e5bef4-4d39-11e6-9ee0-338fa9a55651.png)

**Comment by mattada** [comment]
Colors updated. Need to test more on the scroll bar. What browser are you seeing that on?

**Comment by mbalkon** [comment]
I had been on Chrome, but the scrollbar seems to be gone now!

**Comment by mattada** [comment]
Okay coo. We'll make sure we dont see it when we beta more across other devices too.
