### ISSUE TITLE
Global: Increase the size of H1s by 30-40%

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#67]

**Comment by mattada** [comment]
Was: font-size: rem(60px);
Now: font-size: rem(80px);

**Comment by mbalkon** [comment]
Let's go up to 100px on this. Also, it needs to be all caps (it used to be, but the call-caps styling on this must have fell off somewhere along the way)

**Comment by mattada** [comment]
PS the design comp had these at 75px (150px at 2x)

**Comment by mbalkon** [comment]
Ok. You're right 100px is too big. Can we go back to 90px, and I'll leave it at that.

However, can we also tighten up the line height while you're doing that? They are very spaced out. I'd say it needs to be at least half of what it currently is, possibly even a bit less.

**Comment by mbalkon** [comment]
I'm seeing the size change, but not the line-spacing change on these. Could we reduce the line spacing on the H1s by roughly 50%?
