### ISSUE TITLE
Global: Make sure all H3s look exactly like H2s

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#68]
... Or just retag H3s as H2s.

There are still a lot of places where the H3 styling isn't matching the H2s. It should basically match in every way, except alignment (because we use both center and left alignment with the H2s).

They should all be:
- Proxima Nova
- Regular weight
- Sentence case
- The same size (when I inspect the side-by-side promo boxes on the conference page, these headlines are 40px—this size is good and likely could be used globally.)

To try to clarify further what is wrong with the H3s, they are still smaller than the H2s and many are bold, not regular weight.

**Comment by mattada** [comment]
Pushed, but we may have places that still override this. Probably not, but its possible. IF you see it somewhere else, let me know where.

**Comment by mbalkon** [comment]
So much better!! I still need a couple tweaks:

The headlines of the two stacked promo boxes on the home page are bold, and they should be regular weight—otherwise they are perfect!

Same with almost all of the H2 headlines on the About page.

**Comment by mattada** [comment]
This is updated with issue #76 being globally applied
