### ISSUE TITLE
Global: Adjust hero pattern background colors to #8348ad

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#69]
I think the hex code is wrong in this style. Instead of the background changing to purple, it became a darker shade of blue. The background behind the multi-color pattern should match the current background color of the dropdown navigation.

To clarify, there is a purple and a blue shade and I think that in some styles the style is named purple, but actually has one of the blue hex codes assigned to them.

**Comment by mattada** [comment]
completed with other color fixes on #71
