### ISSUE TITLE
Conference: Background color of patterned ticket price boxes should be #8348ad

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#71]
This is another area where the last change just darkened the shade of blue, rather than changing it to purple instead. It should be true purple.

**Comment by mattada** [comment]
Okay so we should review colors. These are all the colors I have. We pulled these from the comps and I recently shifted most purples to use the `$drkpurple`

Maybe the root issue is in these color codes. 

```
// colors
$yellow:      #e1e723;
$lime:        #e1e723;  // Yellow and lime are the same, but kind of an odd color. 

$fff:         #fff; // Becuase Matt likes to forget # and $ arent the same. 

$ltpurple:    #8348ad;
$purple:      #444a9c;
$drkpurple:   #333679;

$pink:        #ee41aa;

$teal:        #63cbca;

$grey:        #999999;
$ltgrey:      #cccccc;
$black:       #333333;

```

**Comment by mbalkon** [comment]
Ok! Let me review and I'll follow up in just a few minutes...

**Comment by mbalkon** [comment]
Ok, here is what I see in my files... I'm going to leave all colors listed, most are correct, but will make notes by the ones of note:

$yellow:      #e1e723;
$lime:          #e1e723;  // Yellow and lime are the same, but kind of an odd color. 

$fff:         #fff; // Because Matt likes to forget # and $ arent the same. 

**$ltpurple:**    #8348ad; ---> This is what I want when I ask for purple. I'll try to remember to say Light Purple from now on
**$purple:**      #444a9c;  ---> When I ask for blue, this is what I mean. I'll try to remember to say Purple from now on
**$drkpurple:**   #333679;  ---> I don't think there should be any use of this color. Maybe it was used in the landing page, but not the full site, or eyedroppered incorrectly at some point, and was supposed to be #444a9c. Any way you slice it, I don't believe this color should be used anywhere. If you can do some sort of find/replace, I would replace all usage of this color is the Purple/#444a9c.

$pink:        #ee41aa;

$teal:        #63cbca;

$grey:        #999999;
$ltgrey:      #cccccc;
$black:       #333333;

**Comment by mattada** [comment]
Okay I think its all set. New issue. The blue patterns on those blocks is looking a bit strange.

**Comment by mbalkon** [comment]
You're right. Those patterns need to be a dark purple. Note: the dark purple patterns used here are a one-off—meaning these dark purple patterns are _not used anywhere else on the site_. I'll attach them below.

[dark-purple-ticket-price-patterns.zip](https://github.com/factor1/phoenix-design-week-2016/files/374840/dark-purple-ticket-price-patterns.zip)

**Comment by mattada** [comment]
perfect. thanks
