### ISSUE TITLE
About: Polish up text alignment in "learn more" and "check out" boxes

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#77]
The text alignment in these boxes is odd. On other pages, I believe the headlines in both boxes both align horizontally at the top of the box, then the content flows from there (and shorter content will just have a little extra space when positioned next to longer content). 

The text in these two boxes seem to be aligned different... I can't quite figure out how. Could the text align horizontally at the top more like they do on the conference page?

![screenshot 2016-07-19 22 08 10](https://cloud.githubusercontent.com/assets/4261229/16975752/5cf75b3a-4dfe-11e6-87bf-dd47d28099b9.png)

**Comment by mattada** [comment]
Im closing this issue since its the same as #83
