### ISSUE TITLE
Events: Revise event expanders section

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#80]
There are three fixes here (and I apologize if I'm jumping the gun on these requests)
1. There shouldn't be any space between the hero band and when the event bands start. See screenshot below.
2. The events content block should be the same width as the hero box (see the conference page for how this alignment should look.
3. For days with no events, we need to add messaging explaining that events are coming. See screenshot below.

![screenshot 2016-07-19 22 21 11](https://cloud.githubusercontent.com/assets/4261229/16975947/efde0ac4-4dff-11e6-955b-08b9d3468463.png)

![screenshot 2016-07-19 22 23 48](https://cloud.githubusercontent.com/assets/4261229/16975878/88d0de42-4dff-11e6-9714-39242743e097.png)

**Comment by mattada** [comment]
Okay I have 1 & 2 done but I cant quite get the logic right for the fall back. I'll have @erwstout look to see where its wrong on events.php

**Comment by mbalkon** [comment]
This is looking great! On the days that don't have any events, if we have to flow that content into the first column (and we can't fully center that message in the band), could we left-align the text?

![screenshot 2016-07-20 21 22 54](https://cloud.githubusercontent.com/assets/4261229/17011213/270d7abe-4ec0-11e6-8cbb-f7be3420fc03.png)

**Comment by mattada** [comment]
All set!

**Comment by mbalkon** [comment]
Yayayaya!
