### ISSUE TITLE
About: Adjust pattern on the "learn more" box

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#83]
1. There should be a band of the pattern at the top of this box
2. Could we change this pattern to the teal loose diagonals?

![screenshot 2016-07-19 22 32 10](https://cloud.githubusercontent.com/assets/4261229/16976034/b7f2b230-4e00-11e6-8e4d-28446df43794.png)

**Comment by mattada** [comment]
So fun times. This padding is NEVER going to match. Just as content wraps and rolls. See gif
![2016-07-20 14 44 16](https://cloud.githubusercontent.com/assets/10223806/17004155/89f78972-4e88-11e6-9184-2642ad74fbbc.gif)

**Comment by mbalkon** [comment]
Ok. I understand... but I don't understand. Is the text in these boxes top-aligned vertically, or center aligned? I don't understand why the headlines start at different points in the boxes.

If you look at the Conference page, the two boxes at the bottom of the page stay lined up much nicer. Check it out: http://quick.as/54y6t1ZkX 

Could we use these two boxes as a guide and apply the same alignments to the boxes on this About page?

**Comment by mattada** [comment]
Okay I think I have it! @mbalkon will you check?

**Comment by mbalkon** [comment]
Looking SO great! Only one last little fix—for some reason the pattern on the right isn't going all the way to the bottom of the band. Once that is fixed, it is perfect!! See screenshot below:

![screenshot 2016-07-20 21 24 47](https://cloud.githubusercontent.com/assets/4261229/17011232/66896fb8-4ec0-11e6-9e1e-27e6d850fdd5.png)

**Comment by mattada** [comment]
Strange!

**Comment by mattada** [comment]
Hey @erwstout can you help me sort this out? The issue is that the left isnt tall enough, and the leftyleft content isnt filling. Not sure how to adjust the flexbox on that.

**Comment by mbalkon** [comment]
Is leftyleft a term only the pros use?? ;)

**Comment by mattada** [comment]
ha! I was making up dumb names one day. Leftyleft and rightyright.

**Comment by mattada** [comment]
Okay got it! PS the bottom left is just filler, but the bottom right is a set amount. So they may never align perfectly across all views.

**Comment by mbalkon** [comment]
Thank you! We actually don't even need the pattern at the bottom of the white box (I believe this area was just supposed to have pattern across the top).

**Comment by mattada** [comment]
Yeah..... thats not an option. The pattern on the bottom is fill from the BG because the row is taller due to the height of the other column.

**Comment by mbalkon** [comment]
Ok. I don't like it, but at this point I don't think it is a deal-breaker, especially since it is on a page that will likely be less-visited :)

**Comment by mattada** [comment]
The only fix is just as messy. If I add margin to the bottom of that content it would work, but could push the other side in the same way. 

So the lesson here is patterns in split columns like this with top and bottom patterns are dicey.
