### ISSUE TITLE
Conference: Remove weird patch of pattern overlaid on testimonial photo

### ISSUE THREAD

**Issue by mbalkon** [factor1/phoenix-design-week-2016#95]
I have no idea how this got here, but can you remove this little patch of blue pattern from this photo?

![screenshot 2016-07-20 21 27 22](https://cloud.githubusercontent.com/assets/4261229/17011276/e9ff0150-4ec0-11e6-8747-9ce4ddc113f7.png)

**Comment by mattada** [comment]
Got it.
